apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_prefix }}-main-deployment
  labels:
    app: {{ .Values.app_prefix }}-main
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app_prefix }}-main
  template:
    metadata:
      labels:
        app: {{ .Values.app_prefix }}-main
    spec:
      containers:
      - name: {{ .Values.app_prefix }}-main
        image: {{ .Values.main.image }}
        imagePullPolicy: {{ .Values.main.pullPolicy }}
        env:
          - name: DICE_GRPC_TARGET
            value: "{{ .Values.app_prefix }}-envoy:8443"
        ports:
        - containerPort: {{ .Values.main.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_prefix }}-main-service
spec:
  selector:
    app: {{ .Values.app_prefix }}-main
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.main.port }}
      targetPort: {{ .Values.main.port }}
