apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app_prefix }}-nfs1
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs_server }}
    path: {{ .Values.nfs_path }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app_prefix }}-nfs2
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs_server }}
    path: {{ .Values.nfs_path }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app_prefix }}-nfs3
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs_server }}
    path: {{ .Values.nfs_path }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.app_prefix }}-nfs4
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs_server }}
    path: {{ .Values.nfs_path }}
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2